### ISSUE TITLE
Error on cloning using HTTPs

### ISSUE THREAD

**Issue by pburgisser** [camptocamp/camptocamp-devops-stack#329]
When cloning the repo using http protocol, the installer cannot determine REPO_URL:

```
root@ip-10-0-0-45:~/camptocamp-devops-stack/tests/k3s-docker# git clone https://github.com/pburgisser/camptocamp-devops-stack.git
root@ip-10-0-0-45:~/camptocamp-devops-stack/tests/k3s-docker# make debug
CLUSTER_NAME=default
REPO_URL=https://github.com/.git
TARGET_REVISION=thanos
```

**Comment by horni23** [comment]
This change in the Makefile works for me (leaving the quotes):

-ifeq ($(findstring "https",$(REMOTE_URL)),)
+ifeq ($(findstring https,$(REMOTE_URL)),)

**Comment by chornberger-c2c** [comment]
same applies to tests/k3s-docker/Makefile - will create a PR on Monday
