### ISSUE TITLE
Upgrading from 0.14.1 to 0.28.0 leads to a sync failure (EKS)

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/camptocamp-devops-stack#540]
In Applications / kube-prometheus-stack, the kube-prometheus-stack-prometheus fails to apply with the error `error validating data: ValidationError(Prometheus.spec): unknown field "shards" in com.coreos.monitoring.v1.Prometheus.spec`.

It seems to be an open issue with the Prometheus chart (https://github.com/prometheus-community/helm-charts/issues/579). Can we apply a workaround suggested in that issue?

**Comment by mcanevet** [comment]
Hmmm... This is weird, I never encountered this issue. Could do a green-filed upgrade instead of an in-place upgrade, by spawning a new cluster and switch the DNS/LB in front of it?

**Comment by ckaenzig** [comment]
I did a fresh deployment  from scratch on 0.29.0, and I confirm that this issue doesn't happen.

I'm not sure what this means for this issue. Do we support only fresh installs and not upgrades ? Is that viable for production environments ?

**Comment by mcanevet** [comment]
For now we do not support in-place upgrade. I works most of the case, but in the current state of the project I guess it is way too ambitious to support it.

**Comment by ckaenzig** [comment]
Ok thanks, I'm closing this issue.
